### ISSUE TITLE
No código, a variável ret é declarada com valor igual a null, dentro do for existe uma condição que só irá ser satisfeita se a variável ret for diferente de null, porém não existe nenhuma linha que altere o valor da variável ret para que ela seja diferente de null, logo nunca iremos entrar dentro dessa condição.

### ISSUE THREAD

**Issue by Igoress7** [Igoress7/Lab5-Calebe#8]
- Classe: Troco;
- Linhas: 70 - 79;
- Tipo de Erro: Computação/Controle;

**Comment by rodrigogarcia1** [comment]
Corrigido:

 @Override
        public PapelMoeda next() {
            PapelMoeda ret = null;
            for (int i = 0; i <= 7; i++) {
                if (troco.papeisMoeda[i] != null) {
                    ret = troco.papeisMoeda[i];
                    troco.papeisMoeda[i] = null;
                }
            }
            return ret;
        }
